"""change created_at and expires_at to datetime

Revision ID: 26d4d41da949
Revises: ae627f194fb5
Create Date: 2026-07-01 10:54:40.168325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d4d41da949'
down_revision: Union[str, Sequence[str], None] = 'ae627f194fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using='created_at::timestamptz')
    op.alter_column('urls', 'expires_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using='expires_at::timestamptz')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='expires_at::varchar')
    op.alter_column('urls', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='created_at::varchar')
    # ### end Alembic commands ###
