"""create urls table

Revision ID: e6fee46957aa
Revises: 5ae989fa1110
Create Date: 2026-07-01 10:31:26.730987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6fee46957aa'
down_revision: Union[str, Sequence[str], None] = '5ae989fa1110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'original_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('urls', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('urls', 'click_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'click_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('urls', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('urls', 'original_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
